### ISSUE TITLE
Bittrex Ticker Api using Error

### ISSUE THREAD

**Issue by paragonjh** [nlsdfnbch/bitex#111]
Hello, I'm developer in korea.
Thanks for creating an easy to use API.

I want to report and report a bug when using the Bittrex API.

Bittrex's Ticker API usage seems to be wrong.
I think, API call "getticker" instead of "getmarketsummary".

/public/getmarketsummary
=> Used to get the last 24 hour summary of all active exchanges

/public/getticker
=> Used to get the current tick values for a market.

reference page:
https://bittrex.com/Home/Api

### Overview Description

# Steps to Reproduce

1. Call Bitrex ticker API using bitex

# Actual Results
Call getmarketsummary

# Expected Results
Call gettickerAPI

# Reproducibility
Always

# Additional Information:

**Comment by nlsdfnbch** [comment]
Hey @paragonjh,
thanks for contributing! I'm glad you've found the project useful.
Regarding your issue, this was intentional. The `getticker` endpoint offers little data, while `getmarketsummary` returns not only the top level of the market's book, but also candle data (`ohlc`), the market volume, order count for each side of the book, as well as an actual server-created timestamp of the data. 

We found this to be better in every sense, which is why we're using this resource, instead of `getticker`. 

Hope that clears things up!
