### ISSUE TITLE
Add open_orders to BitEx Standardized Methods

### ISSUE THREAD

**Issue by roeiba** [nlsdfnbch/bitex#66]
All major exchanges support a query which returns the opened orders for an account and sometimes for a specific market.  

Usually the result from all exchanges is quite similar, and formatter can be easily created as well.

**Comment by nlsdfnbch** [comment]
If this is true for all exchanges currently implemented, then you're absolutely right. I remember eliminating it from the initial methods, but I cannot remember why. I'll look into the matter -or, if you're willing to, you can add it yourself and submit a pull request.

Much appreciate the feedback!

**Comment by roeiba** [comment]
E.g for poloniex implementation would be:

`
    @return_api_response(fmt.deposit)
    def open_orders(self, **kwargs):
        """
        https://bittrex.com/api/v1.1/market/getopenorders?apikey=API_KEY&market=BTC-LTC
        If market
        """
        return self.private_query('market/getopenorders', params=kwargs)
`

I've done this on my fork for multiple exchanges, I can upload merge request if you guys wish.

**Comment by nlsdfnbch** [comment]
In order to add this method to the standardized methods, it should be available in at least 80% of the exchanges (if some don't implement it, that's fine; An example of this would be the `withdraw()` method, which isn't available on `Yunbi`, for example). So if you're willing to supply the rest of the exchanges as well, we'd love to have your PR. 
Cheers!

**Comment by nlsdfnbch** [comment]
Added to standardized methods in `2.0`
